name: Echo service

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      branch:
        required: false
        default: $default-branch
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test branch
        env:
          DEFAULT_BRANCH: ${{ inputs.branch }}
        run: |
          echo "messing around"
          echo $DEFAULT_BRANCH
