name: Echo service

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test branch
        env:
          DEFAULT_BRANCH: ${{ github.event.inputs.branch || $default-branch }}
        run: |
          echo "messing around"
          echo $DEFAULT_BRANCH
